-- ============================================================
-- SUPABASE SQL MIGRATION: VEHICLES MANAGEMENT
-- System: SAGA Washing Center
-- ============================================================

-- 1. Create Vehicles Table
CREATE TABLE IF NOT EXISTS public.vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_no TEXT UNIQUE NOT NULL,      -- e.g. CAD8590, WP-CAD-8590
    category TEXT NOT NULL,               -- Car, Double Cab, Bike, Lorry
    model TEXT DEFAULT '',                -- e.g. Prius, Hilux, Canter
    status TEXT NOT NULL DEFAULT 'available', -- available, busy, maintenance
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ensure Trips table has vehicle_no column
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS vehicle_no TEXT;
ALTER TABLE public.trips ADD COLUMN IF NOT EXISTS vehicle_id TEXT;

-- 3. Enable Row Level Security (RLS) & Add Access Policy
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon vehicles') THEN
        CREATE POLICY "Allow anon vehicles" ON public.vehicles FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 4. Indexes for Fast Performance
CREATE INDEX IF NOT EXISTS idx_vehicles_vehicle_no ON public.vehicles(vehicle_no);
CREATE INDEX IF NOT EXISTS idx_vehicles_category ON public.vehicles(category);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON public.vehicles(status);
CREATE INDEX IF NOT EXISTS idx_trips_vehicle_no ON public.trips(vehicle_no);
