-- ============================================================
-- SUPABASE SQL MIGRATION: TRASH / RECYCLE BIN
-- System: SAGA Washing Center
-- Anything deleted (customer/driver/vehicle/item/trip/order) is snapshotted
-- here first, kept for 7 days (purged lazily on read — see DB.getTrash),
-- and can be restored. Also the mechanism "Undo" uses on the Recent
-- Actions page for Delete-type entries.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.trash (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,      -- 'Customer' | 'Driver' | 'Vehicle' | 'Item' | 'Trip' | 'Order'
  entity_label TEXT NOT NULL,     -- human label, e.g. batch_id / hotel_name / vehicle_no
  payload JSONB NOT NULL,         -- full snapshot needed to restore
  deleted_by TEXT,
  deleted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.trash ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'trash' AND policyname = 'authenticated read trash') THEN
    CREATE POLICY "authenticated read trash" ON public.trash FOR SELECT USING (auth.role() = 'authenticated');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'trash' AND policyname = 'admin write trash') THEN
    CREATE POLICY "admin write trash" ON public.trash FOR INSERT WITH CHECK (public.current_user_role() = 'admin');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'trash' AND policyname = 'admin delete trash') THEN
    CREATE POLICY "admin delete trash" ON public.trash FOR DELETE USING (public.current_user_role() = 'admin');
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_trash_deleted_at ON public.trash(deleted_at);
