-- ============================================================
-- SUPABASE SQL MIGRATION: EXPENSES & CHEMICAL MANAGEMENT
-- System: SAGA Washing Center
-- ============================================================

-- 1. Create Chemicals Master Catalog Table
CREATE TABLE IF NOT EXISTS public.chemicals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chemical_id TEXT UNIQUE NOT NULL, -- e.g. CHM-0001
    name TEXT NOT NULL,               -- e.g. Chemical Name
    unit TEXT NOT NULL DEFAULT 'kg',   -- kg, ml, L
    package_size TEXT DEFAULT '',     -- e.g. 5 kg
    status TEXT DEFAULT 'Active',     -- Active / Inactive
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Chemical Stock Ledger Table (IN / OUT / BAL Matrix)
CREATE TABLE IF NOT EXISTS public.chemical_ledger (
    id TEXT PRIMARY KEY,
    expense_id TEXT,                    -- e.g. EXP-2026-00001 (for IN purchases)
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    chemical_id TEXT NOT NULL,          -- e.g. CHM-0001
    chemical_name TEXT,
    type TEXT NOT NULL CHECK (type IN ('IN', 'OUT')),
    qty_in NUMERIC(12,2) DEFAULT 0.00,
    qty_out NUMERIC(12,2) DEFAULT 0.00,
    unit TEXT DEFAULT 'kg',
    unit_price NUMERIC(12,2) DEFAULT 0.00,
    total_amount NUMERIC(12,2) DEFAULT 0.00,
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create General Operational Expenses Table
CREATE TABLE IF NOT EXISTS public.general_expenses (
    id TEXT PRIMARY KEY,
    expense_id TEXT UNIQUE NOT NULL,    -- e.g. EXP-2026-00002
    expense_name TEXT NOT NULL,         -- e.g. Stationery, Diesel, Electricity
    expense_category TEXT DEFAULT 'General Operational', -- e.g. Transport Cost, Utilities, etc.
    expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    months_covered INT NOT NULL DEFAULT 1,
    monthly_averaged_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    payment_method TEXT DEFAULT 'Cash',
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure expense_category column exists on existing general_expenses table
ALTER TABLE public.general_expenses ADD COLUMN IF NOT EXISTS expense_category TEXT DEFAULT 'General Operational';


-- 5. Enable Row Level Security (RLS) & Add Policies
ALTER TABLE public.chemicals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chemical_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.general_expenses ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon chemicals') THEN
        CREATE POLICY "Allow anon chemicals" ON public.chemicals FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon chemical_ledger') THEN
        CREATE POLICY "Allow anon chemical_ledger" ON public.chemical_ledger FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon general_expenses') THEN
        CREATE POLICY "Allow anon general_expenses" ON public.general_expenses FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_chemical_ledger_date ON public.chemical_ledger(date);
CREATE INDEX IF NOT EXISTS idx_chemical_ledger_chem_id ON public.chemical_ledger(chemical_id);
CREATE INDEX IF NOT EXISTS idx_general_expenses_date ON public.general_expenses(expense_date);
