-- ============================================================
-- SUPABASE SQL MIGRATION: EXPENSES v2 (Cash Book / Category View)
-- System: SAGA Washing Center
--
-- Fully replaces the old Chemical Stock Register + General Expenses
-- schema (supabase_expenses_migration.sql) with a spreadsheet-style
-- "Cash Book" (categories with reorderable expense sub-columns) and a
-- "Category View" (flat filterable list of the same underlying data).
--
-- DESTRUCTIVE: drops chemicals, chemical_ledger, general_expenses and
-- ALL data in them. There is no migration path from the old schema —
-- the chemical-costing domain (IN/OUT/BAL stock, weighted-average
-- COGS) has no equivalent in the new design. Run this once, then
-- deploy the accompanying JS changes immediately after.
-- ============================================================

DROP TABLE IF EXISTS public.chemical_ledger;
DROP TABLE IF EXISTS public.general_expenses;
DROP TABLE IF EXISTS public.chemicals;

-- 1. Categories — top-level Cash Book columns (e.g. "Vehicle Expenses")
CREATE TABLE IF NOT EXISTS public.expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id TEXT UNIQUE NOT NULL,   -- e.g. CAT-00001
    name TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,  -- left-right order among categories
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Expense types — sub-columns nested under a category (e.g. "Fuel")
CREATE TABLE IF NOT EXISTS public.expense_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_type_id TEXT UNIQUE NOT NULL,  -- e.g. EXP-00001
    name TEXT NOT NULL,
    category_id TEXT NOT NULL REFERENCES public.expense_categories(category_id) ON DELETE CASCADE,
    sort_order INT NOT NULL DEFAULT 0,     -- left-right order within the parent category
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Entries — one Cash Book row (a Date + Description journal line)
CREATE TABLE IF NOT EXISTS public.expense_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_date DATE NOT NULL,
    description TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Amounts — one filled grid cell (row x expense-type intersection)
CREATE TABLE IF NOT EXISTS public.expense_amounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL REFERENCES public.expense_entries(id) ON DELETE CASCADE,
    expense_type_id TEXT NOT NULL REFERENCES public.expense_types(expense_type_id) ON DELETE CASCADE,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(entry_id, expense_type_id)
);

-- 5. Enable Row Level Security (RLS) & Add Policies
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_types      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_entries    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_amounts    ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon expense_categories') THEN
        CREATE POLICY "Allow anon expense_categories" ON public.expense_categories FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon expense_types') THEN
        CREATE POLICY "Allow anon expense_types" ON public.expense_types FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon expense_entries') THEN
        CREATE POLICY "Allow anon expense_entries" ON public.expense_entries FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon expense_amounts') THEN
        CREATE POLICY "Allow anon expense_amounts" ON public.expense_amounts FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 6. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_expense_types_category      ON public.expense_types(category_id);
CREATE INDEX IF NOT EXISTS idx_expense_entries_date         ON public.expense_entries(entry_date);
CREATE INDEX IF NOT EXISTS idx_expense_amounts_entry        ON public.expense_amounts(entry_id);
CREATE INDEX IF NOT EXISTS idx_expense_amounts_expense_type ON public.expense_amounts(expense_type_id);

-- 7. ID-counter RPCs — atomic, reusing the existing public.id_counters
-- table and the same INSERT...ON CONFLICT DO UPDATE...RETURNING idiom
-- as next_batch_id()/next_invoice_number() (see
-- supabase_id_generation_fix.sql). 5-digit, zero-padded, and NOT
-- month-scoped (categories/expense types aren't reset monthly like
-- batch/invoice numbers) — call with a fixed prefix ('CAT-'/'EXP-').
--
-- Note: 'EXP-' here is a different id_counters.counter_key than the
-- old per-transaction expense IDs used ('EXP-2026-' etc, now retired
-- along with generateExpenseId()), so there's no collision — just a
-- reused human-readable prefix letter for a different ID space.
--
-- id_counters is normally created by supabase_id_generation_fix.sql;
-- guarded here too so this file is self-contained on a fresh project.
CREATE TABLE IF NOT EXISTS public.id_counters (
  counter_key   text PRIMARY KEY,
  current_value integer NOT NULL DEFAULT 0
);
ALTER TABLE public.id_counters ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.next_category_id(prefix text)
RETURNS text
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_seq integer;
BEGIN
  INSERT INTO public.id_counters (counter_key, current_value)
  VALUES (prefix, 1)
  ON CONFLICT (counter_key)
  DO UPDATE SET current_value = public.id_counters.current_value + 1
  RETURNING current_value INTO v_seq;

  RETURN prefix || lpad(v_seq::text, 5, '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.next_expense_type_id(prefix text)
RETURNS text
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_seq integer;
BEGIN
  INSERT INTO public.id_counters (counter_key, current_value)
  VALUES (prefix, 1)
  ON CONFLICT (counter_key)
  DO UPDATE SET current_value = public.id_counters.current_value + 1
  RETURNING current_value INTO v_seq;

  RETURN prefix || lpad(v_seq::text, 5, '0');
END;
$$;
